services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: ticket-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticketDb 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Infrastructure/Database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  redis:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly no --save ""
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ticket-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC (để C# client dùng)
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
  
#  api:
#     ports:
#       - "5105:8080"
#     build:
#       context: . 
#       dockerfile: TicketManagement.Api/Dockerfile
#     container_name: ticket-api
#     depends_on:
#       - redis
#       - postgres
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:8080
#     env_file:
#       - TicketManagement.Api/.env.docker
  
volumes:
  postgres_data:
  qdrant_data:
